-- Create the Certifications Table
create table public.certifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null,
  name text not null,
  provider text not null,
  category text not null,
  level text not null,
  rating numeric default 0,
  difficulty numeric default 0,
  popularity numeric default 0,
  job_market numeric default 0,
  description text,
  duration text,
  cost text,
  prerequisites text,
  exam_format text,
  key_skills text[],
  career_paths text[],
  link text
);

-- RLS
alter table public.certifications enable row level security;

-- Policies
create policy "Enable read access for all users" on public.certifications for select using (true);
create policy "Enable insert for all users" on public.certifications for insert with check (true);
create policy "Enable update for all users" on public.certifications for update using (true);
create policy "Enable delete for all users" on public.certifications for delete using (true);
