-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Categories Table
create table if not exists public.categories (
  id uuid default uuid_generate_v4() primary key,
  name text not null unique,
  color text default '#3b82f6',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tools Table
create table if not exists public.tools (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  description text,
  category_id uuid references public.categories(id),
  url text,
  color text,
  icon text,
  command text,
  is_hidden boolean default false,
  tags text[],
  articles jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Books Table
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  description text,
  url text,
  cover_image text,
  category text,
  level text,
  tags text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Useful Links Table
create table if not exists public.useful_links (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text not null,
  category text,
  tags text[],
  icon text,
  icon_name text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Platforms Table
create table if not exists public.platforms (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text,
  icon text,
  features text[],
  type text,
  pricing_model text,
  rating numeric,
  founded text,
  hackers text,
  notable_companies text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Certifications Table
create table if not exists public.certifications (
  id bigint generated by default as identity primary key,
  code text,
  name text not null,
  provider text,
  category text,
  level text,
  rating numeric,
  difficulty numeric,
  popularity numeric,
  job_market numeric,
  description text,
  duration text,
  cost text,
  prerequisites text,
  exam_format text,
  key_skills text[],
  career_paths text[],
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Downloads Table
create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text,
  icon text,
  category text,
  size text,
  version text,
  os text[],
  code text,
  type text,
  team text,
  popularity numeric,
  key_features text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 8. Frameworks Table
create table if not exists public.frameworks (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text,
  icon text,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 9. Breach Services Table
create table if not exists public.breach_services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text,
  icon text,
  type text,
  features text[],
  checks text[],
  category text,
  tags text[],
  key_features text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 10. YouTubers Table
create table if not exists public.youtubers (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  url text,
  icon text,
  category text,
  subscribers text,
  topics text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (Row Level Security)
alter table public.categories enable row level security;
alter table public.tools enable row level security;
alter table public.books enable row level security;
alter table public.useful_links enable row level security;
alter table public.platforms enable row level security;
alter table public.certifications enable row level security;
alter table public.downloads enable row level security;
alter table public.frameworks enable row level security;
alter table public.breach_services enable row level security;
alter table public.youtubers enable row level security;

-- Create Policies (Public Access)
create policy "Public Access" on public.categories for all using (true) with check (true);
create policy "Public Access" on public.tools for all using (true) with check (true);
create policy "Public Access" on public.books for all using (true) with check (true);
create policy "Public Access" on public.useful_links for all using (true) with check (true);
create policy "Public Access" on public.platforms for all using (true) with check (true);
create policy "Public Access" on public.certifications for all using (true) with check (true);
create policy "Public Access" on public.downloads for all using (true) with check (true);
create policy "Public Access" on public.frameworks for all using (true) with check (true);
create policy "Public Access" on public.breach_services for all using (true) with check (true);
create policy "Public Access" on public.youtubers for all using (true) with check (true);
