-- Existing: Books & Useful Links (Keep or Re-run if safe, but using IF NOT EXISTS is better practice, but for this snippet I'll provide the full set)

-- 1. Platforms
create table if not exists public.platforms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  url text,
  category text, -- 'Salesforce', 'ServiceNow', 'SAP', 'Workday', 'Oracle'
  tags text[],
  features text[], -- JSON array or text array. Text array is easier for simple lists.
  icon_name text,
  popularity_score integer default 0
);

-- 2. Certifications
create table if not exists public.certifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  provider text, -- e.g. 'OffSec', 'SANS'
  description text,
  category text, -- 'Red Team', 'Blue Team'
  level text, -- 'Beginner', 'Intermediate', 'Advanced'
  price text, -- e.g. '$1499'
  url text,
  exam_type text, -- 'Practical', 'Multiple Choice'
  tags text[]
);

-- 3. Downloads
create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  category text, -- 'Cheat Sheets', 'Wordlists', 'Scripts', 'VMs'
  url text not null,
  format text, -- 'PDF', 'TXT', 'ZIP'
  size text, -- '2.5 MB'
  author text,
  tags text[]
);

-- 4. Frameworks
create table if not exists public.frameworks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  category text, -- 'Regulatory', 'Standards', 'Risk Management'
  url text, 
  author text,
  tags text[]
);

-- 5. Breach Services
create table if not exists public.breach_services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  category text, -- 'Free Services', 'Premium Services', 'Intelligence Platforms'
  url text,
  type text, -- 'Free', 'Paid'
  key_features text[],
  tags text[],
  icon_name text
);

-- 6. YouTubers
create table if not exists public.youtubers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  url text not null,
  category text, -- 'Educational', 'News', 'Tutorials'
  tags text[]
);

-- Enable RLS for all
alter table public.platforms enable row level security;
alter table public.certifications enable row level security;
alter table public.downloads enable row level security;
alter table public.frameworks enable row level security;
alter table public.breach_services enable row level security;
alter table public.youtubers enable row level security;

-- Create Policies (Open for now)
create policy "Enable all access for platforms" on public.platforms for all using (true) with check (true);
create policy "Enable all access for certifications" on public.certifications for all using (true) with check (true);
create policy "Enable all access for downloads" on public.downloads for all using (true) with check (true);
create policy "Enable all access for frameworks" on public.frameworks for all using (true) with check (true);
create policy "Enable all access for breach_services" on public.breach_services for all using (true) with check (true);
create policy "Enable all access for youtubers" on public.youtubers for all using (true) with check (true);
