INSERT INTO public.certifications (
    code, name, provider, category, level, rating, difficulty, popularity, job_market, description, duration, cost, prerequisites, exam_format, key_skills, career_paths, link
) VALUES
('OSCP', 'Offensive Security Certified Professional', 'Offensive Security', 'Red Team', 'Intermediate', 4, 5, 5, 5, 'Hands-on penetration testing certification focusing on practical exploitation skills.', '90 days lab + exam', '$1,499', 'Basic networking and Linux knowledge', '24-hour practical exam + 24-hour report', ARRAY['Penetration Testing', 'Exploitation', 'Report Writing', 'Linux', 'Windows'], ARRAY['Penetration Tester', 'Security Consultant', 'Red Team Operator'], 'https://www.offsec.com/'),
('OSEP', 'Offensive Security Experienced Penetration Tester', 'Offensive Security', 'Red Team', 'Advanced', 5, 4, 5, 5, 'Advanced evasion techniques and modern penetration testing methodologies.', '90 days lab + exam', '$1,499', 'OSCP or equivalent experience', '48-hour practical exam + 24-hour report', ARRAY['Evasion Techniques', 'Advanced Exploitation', 'AV Bypass', 'Lateral Movement'], ARRAY['Senior Penetration Tester', 'Red Team Lead', 'Security Researcher'], 'https://www.offsec.com/'),
('OSWE', 'Offensive Security Web Expert', 'Offensive Security', 'Red Team', 'Advanced', 5, 3, 4, 5, 'Advanced web application security testing and source code review.', '90 days lab + exam', '$1,499', 'Web development and OSCP knowledge', '48-hour practical exam + 24-hour report', ARRAY['Web Application Security', 'Source Code Review', 'Custom Exploits'], ARRAY['Web Application Penetration Tester', 'Security Researcher'], 'https://www.offsec.com/'),
('CEH', 'Certified Ethical Hacker', 'EC-Council', 'Red Team', 'Beginner', 2, 5, 3, 4, 'Entry-level ethical hacking certification covering basic penetration testing concepts.', '5 days training', '$1,199', 'Basic IT security knowledge', '4-hour multiple choice exam', ARRAY['Ethical Hacking', 'Vulnerability Assessment', 'Basic Penetration Testing'], ARRAY['Junior Penetration Tester', 'Security Analyst'], 'https://www.eccouncil.org/'),
('CRTP', 'Certified Red Team Professional', 'PentesterAcademy', 'Red Team', 'Intermediate', 3, 3, 4, 4, 'Active Directory focused red team certification with practical labs.', '30 days lab + exam', '$249', 'Basic Windows and AD knowledge', '24-hour practical exam', ARRAY['Active Directory', 'Lateral Movement', 'Privilege Escalation'], ARRAY['Red Team Operator', 'Penetration Tester'], 'https://www.elearnsecurity.com/'),
('GPEN', 'GIAC Penetration Tester', 'SANS/GIAC', 'Red Team', 'Intermediate', 3, 4, 4, 5, 'Comprehensive penetration testing certification from SANS Institute.', '6 days training', '$7,000+', 'Basic security and networking knowledge', '4-hour proctored exam', ARRAY['Penetration Testing', 'Vulnerability Assessment', 'Network Security'], ARRAY['Penetration Tester', 'Security Consultant'], 'https://www.giac.org/'),
('GCIH', 'GIAC Certified Incident Handler', 'SANS/GIAC', 'Blue Team', 'Intermediate', 3, 4, 5, 5, 'Incident response and digital forensics certification.', '6 days training', '$7,000+', 'Basic security knowledge', '4-hour proctored exam', ARRAY['Incident Response', 'Digital Forensics', 'Malware Analysis'], ARRAY['Incident Response Analyst', 'SOC Analyst', 'Digital Forensics Examiner'], 'https://www.giac.org/'),
('GCFA', 'GIAC Certified Forensic Analyst', 'SANS/GIAC', 'Blue Team', 'Advanced', 4, 3, 4, 5, 'Advanced digital forensics and incident response certification.', '6 days training', '$7,000+', 'GCIH or equivalent experience', '4-hour proctored exam', ARRAY['Digital Forensics', 'Memory Analysis', 'Timeline Analysis'], ARRAY['Digital Forensics Examiner', 'Incident Response Lead'], 'https://www.giac.org/'),
('GSEC', 'GIAC Security Essentials', 'SANS/GIAC', 'Blue Team', 'Beginner', 2, 5, 4, 4, 'Foundation-level security certification covering essential security concepts.', '6 days training', '$7,000+', 'Basic IT knowledge', '4-hour proctored exam', ARRAY['Security Fundamentals', 'Risk Management', 'Network Security'], ARRAY['Security Analyst', 'SOC Analyst', 'Security Consultant'], 'https://www.giac.org/'),
('GNFA', 'GIAC Network Forensic Analyst', 'SANS/GIAC', 'Blue Team', 'Advanced', 4, 2, 3, 4, 'Network traffic analysis and forensics certification.', '6 days training', '$7,000+', 'Network and security fundamentals', '4-hour proctored exam', ARRAY['Network Forensics', 'Traffic Analysis', 'Intrusion Detection'], ARRAY['Network Security Analyst', 'Digital Forensics Examiner'], 'https://www.giac.org/'),
('CySA+', 'CompTIA Cybersecurity Analyst', 'CompTIA', 'Blue Team', 'Intermediate', 3, 4, 4, 5, 'Cybersecurity analyst certification focusing on threat detection and analysis.', 'Self-paced', '$370', 'Network+ and Security+ recommended', '165 questions, 165 minutes', ARRAY['Threat Analysis', 'Vulnerability Assessment', 'Incident Response'], ARRAY['SOC Analyst', 'Cybersecurity Analyst', 'Threat Hunter'], 'https://www.comptia.org/'),
('BTLO', 'Blue Team Level 1', 'Security Blue Team', 'Blue Team', 'Beginner', 2, 3, 4, 4, 'Entry-level blue team certification with hands-on labs.', 'Self-paced', '$399', 'Basic IT knowledge', '24-hour practical exam', ARRAY['SOC Operations', 'Log Analysis', 'Incident Response'], ARRAY['SOC Analyst', 'Security Analyst'], 'https://securityblue.team/'),
('CISSP', 'Certified Information Systems Security Professional', 'ISC2', 'Management', 'Advanced', 4, 5, 5, 5, 'Management-level security certification covering eight security domains.', 'Self-paced', '$749', '5 years of security experience', '100-150 questions, 3 hours', ARRAY['Security Management', 'Risk Management', 'Governance'], ARRAY['CISO', 'Security Manager', 'Security Architect'], 'https://www.isc2.org/'),
('CISM', 'Certified Information Security Manager', 'ISACA', 'Management', 'Advanced', 4, 4, 4, 5, 'Information security management and governance certification.', 'Self-paced', '$760', '5 years of security experience', '150 questions, 4 hours', ARRAY['Security Management', 'Governance', 'Risk Management'], ARRAY['Security Manager', 'CISO', 'Security Consultant'], '#');
