-- Copy everything below and paste it into the SQL Editor in your Supabase Dashboard

-- 1. Create the Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  color text
);

-- 2. Create the Tools Table
create table public.tools (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  category_id bigint references public.categories(id),
  color text,
  tags text[],
  articles jsonb default '[]'::jsonb,
  is_hidden boolean default false
);

-- 3. Enable Security (Row Level Security)
alter table public.categories enable row level security;
alter table public.tools enable row level security;

-- 4. Create Access Policies (Allow all operations for now)
-- READ
create policy "Enable read access for all users" on public.categories for select using (true);
create policy "Enable read access for all users" on public.tools for select using (true);

-- INSERT
create policy "Enable insert for all users" on public.categories for insert with check (true);
create policy "Enable insert for all users" on public.tools for insert with check (true);

-- UPDATE
create policy "Enable update for all users" on public.categories for update using (true);
create policy "Enable update for all users" on public.tools for update using (true);

-- DELETE
create policy "Enable delete for all users" on public.categories for delete using (true);
create policy "Enable delete for all users" on public.tools for delete using (true);
