-- Tool Submissions Schema
-- Execute this in Supabase SQL Editor after setting up Google OAuth

-- 1. Create tool_submissions table
CREATE TABLE IF NOT EXISTS public.tool_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_email TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    tags TEXT[],
    color TEXT DEFAULT '#64748b',
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by UUID REFERENCES auth.users(id),
    review_notes TEXT
);

-- 2. Create admin_users table (for both admin auth and submission review)
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create helper function to check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_users WHERE admin_users.user_id = $1
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Enable RLS on tool_submissions
ALTER TABLE public.tool_submissions ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for tool_submissions

-- Users can insert their own submissions
CREATE POLICY "Users can create submissions"
    ON public.tool_submissions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users can view their own submissions
CREATE POLICY "Users can view own submissions"
    ON public.tool_submissions
    FOR SELECT
    USING (auth.uid() = user_id);

-- Admins can view all submissions
CREATE POLICY "Admins can view all submissions"
    ON public.tool_submissions
    FOR SELECT
    USING (public.is_admin(auth.uid()));

-- Admins can update all submissions (for approval/rejection)
CREATE POLICY "Admins can update submissions"
    ON public.tool_submissions
    FOR UPDATE
    USING (public.is_admin(auth.uid()));

-- 6. Update existing RLS policies for tools and categories to require admin

-- Drop existing permissive policies
DROP POLICY IF EXISTS "Enable insert for all users" ON public.tools;
DROP POLICY IF EXISTS "Enable update for all users" ON public.tools;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.tools;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.categories;
DROP POLICY IF EXISTS "Enable update for all users" ON public.categories;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.categories;

-- Keep read access for everyone
-- (The existing "Enable read access for all users" policies remain)

-- Add admin-only write policies
CREATE POLICY "Admins can insert tools"
    ON public.tools
    FOR INSERT
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Admins can update tools"
    ON public.tools
    FOR UPDATE
    USING (public.is_admin(auth.uid()));

CREATE POLICY "Admins can delete tools"
    ON public.tools
    FOR DELETE
    USING (public.is_admin(auth.uid()));

CREATE POLICY "Admins can insert categories"
    ON public.categories
    FOR INSERT
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Admins can update categories"
    ON public.categories
    FOR UPDATE
    USING (public.is_admin(auth.uid()));

CREATE POLICY "Admins can delete categories"
    ON public.categories
    FOR DELETE
    USING (public.is_admin(auth.uid()));

-- 7. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_submissions_status ON public.tool_submissions(status);
CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON public.tool_submissions(user_id);
